const express = require("express");
const router = express.Router();
const { check, validationResult } = require("express-validator");

const Artist = require("../models/Artist.js");

// @route     GET api/artworks
// @phone      Get all artworkss generated by user
// @access   public
router.get("/", async (req, res) => {
  try {
    let data = await Artist.find(req.params);
    res.send(data);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});

router.post("/", async (req, res) => {
  try {
    const newartist = new Artist(req.body);
    const artist = await newartist.save();
    res.send(artist);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});

router.put("/:_id", async (req, res) => {
  try {
    let data = await Artist.updateOne(req.params, { $set: req.body });
    res.send(data);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});
router.delete("/:_id", async (req, res) => {
  try {
    let data = await Artist.deleteOne(req.params);
    res.send(data);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});

module.exports = router;
