const express = require("express");
const router = express.Router();
const { check, validationResult } = require("express-validator");

const Order = require("../models/Orders.js");

// @route     GET api/orders
// @phone      Get all orders generated by user
// @access   public
router.get("/", async (req, res) => {
  try {
    const order = await Order.find({}).sort({
      date: -1, //sorting starting from the recent date
    });
    res.json(order);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});

// @route     POST api/orders
// @phone      Add new orders
// @access    Private
router.post("/", async (req, res) => {
  //   const errors = validationResult(req);
  //   if (!errors.isEmpty()) {
  //     return res.status(400).json({ errors: errors.array() });
  //   }

  const { ship_id, user_id, artworks, delivery_status } = req.body;

  try {
    const neworder = new Order({
      ship_id,
      user_id,
      artworks,
      delivery_status,
    });

    const order = await neworder.save();

    res.json(order);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});
router.put("/:_id", async (req, res) => {
  let data = await Order.updateOne(req.params, { $set: req.body });
  res.send(data);
});
router.delete("/:_id", async (req, res) => {
  console.log(req.params);
  let data = await Order.deleteOne(req.params);
  res.send(data);
});
module.exports = router;
