const express = require("express");
const router = express.Router();
const { check, validationResult } = require("express-validator");

const Reviews = require("../models/Reviews.js");

// @route     GET api/artworks
// @phone      Get all artworkss generated by user
// @access   public
router.get("/", async (req, res) => {
  try {
    const reviews = await Reviews.find({}).sort({
      date: -1, //sorting starting from the recent date
    });
    res.json(reviews);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});

// @route     POST api/artworks
// @phone      Add new artworks
// @access    Private
router.post("/", async (req, res) => {
  //   const errors = validationResult(req);
  //   if (!errors.isEmpty()) {
  //     return res.status(400).json({ errors: errors.array() });
  //   }

  const { rating, comment, reviewerid } = req.body;

  try {
    const newreviews = new Reviews({
      rating,
      comment,
      reviewerid,
    });

    const reviews = await newreviews.save();

    res.json(reviews);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});
router.put("/:_id", async (req, res) => {
  let data = await Reviews.updateOne(req.params, { $set: req.body });
  res.send(data);
});
router.delete("/:_id", async (req, res) => {
  let data = await Reviews.deleteOne(req.params);
  res.send(data);
});

module.exports = router;
